### ISSUE TITLE
Review 11-9-2023

### ISSUE THREAD

**Issue by nathan-chappell** [aromic1/Mapper#6]
Related branch: [review/11-9-2023](https://github.com/aromic1/Mapper/tree/review/11-9-2023)

I made some changes to the tests.  In particular, in the main test that you wrote I commented out [the lines](https://github.com/aromic1/Mapper/blob/9bc96e8d9f9fcb2321bdcfc1725f066cc628071d/Mapper/UnitTests/UnitTests1.cs#L211) asserting that the property "IsGeometryShape" is mapped.  *You tell me,* should that property get mapped?  Double check, and figure out what the problem is if there is one.  If there is no problem, and the property in fact should not be mapped, then you need to fix the tests to reflect that.

Also, I commented out [a line](https://github.com/aromic1/Mapper/blob/9bc96e8d9f9fcb2321bdcfc1725f066cc628071d/Mapper/Mappings/Mapper.cs#L447) where you check if a type is a record type or not and throw an exception.  I don't know if this was doing anything important, but I removed it and all tests continued to pass, while one that was failing started to pass.

Fix up these two issues and that's about it from me, unless we want to do some refactoring/cleanup .

**Comment by aromic1** [comment]
Both issues fixed.
